export interface Step { key: string; title: string; why: string; todo: string[]; to?: string; cta?: string; auto?: 'events' | 'tasks' | 'daily' | 'decisions'; due?: string }
export const STEPS: Step[] = [
 { key: 'look', title: 'Make the app comfortable', why: 'You will use this every day, so it should feel calm and easy to read.', todo: ['Open Settings.', 'Pick a theme, text size and font you like.', 'Come back here and press "I did this".'], to: '/settings', cta: 'Open Settings' },
 { key: 'dates', title: 'Load your university deadlines', why: 'Deadlines are the skeleton of the project. Missing one costs marks.', todo: ['Open Timeline.', 'Press "Load UH 2026/27 dates".', 'Check them against Canvas (the handbook is a draft).'], to: '/timeline', cta: 'Open Timeline', auto: 'events' },
 { key: 'topic', title: 'Choose your project idea', why: 'The longer choosing takes, the less time you have to build.', todo: ['Look at the project list.', 'Pick one idea you could explain in one sentence.', 'Write it down as a decision (Decisions page).'], to: '/decisions', cta: 'Record the decision', due: '2026-10-07' },
 { key: 'supervisor', title: 'Email your supervisor and book a meeting', why: 'Your supervisor marks most of the project. The first meeting is your responsibility.', todo: ['Check Canvas for your supervisor name (due Wed 7 Oct).', 'Email them: introduce yourself, name your idea, ask for a time between 8 and 14 Oct.', 'Fill in the Selection Form 24 hours before the meeting.'], due: '2026-10-14' },
 { key: 'selection', title: 'Submit Project Selection on Canvas', why: 'This is Assignment 1. It is a hard deadline.', todo: ['Open the Project Selection assignment on Canvas.', 'Submit before 17:00.'], due: '2026-10-15' },
 { key: 'tasks', title: 'Break the project into small tasks', why: 'Big projects feel impossible. Small tasks do not.', todo: ['Open Tasks.', 'Add at least 3 tasks. Mark the essential ones "core".', 'Keep "stretch" for extras only.'], to: '/tasks', cta: 'Open Tasks', auto: 'tasks' },
 { key: 'day', title: 'Do your first Start Day', why: 'A daily habit beats long, rare work sessions.', todo: ['Open Today.', 'Answer the two questions.'], to: '/today', cta: 'Start my day', auto: 'daily' },
 { key: 'decision', title: 'Record one decision with a reason', why: 'The report rewards justified choices. Writing them down now saves hours later.', todo: ['Open Decisions.', 'Write the question, what you chose and why.'], to: '/decisions', cta: 'Open Decisions', auto: 'decisions' },
 { key: 'outline', title: 'Write and submit your Project Outline', why: 'Worth 10%. Needs aims, Gantt chart, risks and ethics check. It must be your own writing.', todo: ['Draft it with your supervisor’s feedback.', 'Aim to finish Mon 9 Nov.', 'Submit on Canvas before Mon 16 Nov 17:00.'], due: '2026-11-16' },
 { key: 'logbook', title: 'Start your logbook habit', why: 'Logbooks are marked. Write them within 24 hours of each supervisor meeting.', todo: ['After each meeting, note what you discussed.', 'Submit on Canvas before each logbook closes (first: Fri 30 Oct, 23:00).'], due: '2026-10-30' },
]
