export interface Step {
  key: string; title: string; why: string; todo: string[]; to?: string; cta?: string;
  auto?: 'events' | 'tasks' | 'daily' | 'decisions' | 'profiles'; due?: string;
}
export const STEPS: Step[] = [
  { key: 'look', title: 'Make the app comfortable to read', why: 'You will use this every day. Low cognitive load starts with the basics.', todo: ['Open Settings.', 'Pick a theme, text size, font and spacing you like.', 'Return here and press "I did this".'], to: '/settings', cta: 'Open Settings' },
  { key: 'profile', title: 'Tell the system about your project', why: 'Dates, deadlines, recommendations and planning all adapt to your specific project.', todo: ['Open Profile.', 'Fill in project title, supervisor, start/submission dates and daily capacity.', 'Save and return.'], to: '/profile', cta: 'Open Profile', auto: 'profiles', due: '2026-10-09' },
  { key: 'dates', title: 'Load university deadlines', why: 'Missing a deadline costs marks. The planning engine needs them first.', todo: ['Open Timeline.', 'Press "Load UH 2026/27 dates".', 'Cross-check against Canvas (this handbook is v0.9 draft).'], to: '/timeline', cta: 'Open Timeline', auto: 'events' },
  { key: 'topic', title: 'Pick a project idea you can explain in one sentence', why: 'The longer choosing takes, the less time you have to build and write.', todo: ['Browse the Project library.', 'Shortlist 2–3 ideas.', 'Write a one-sentence version of your favourite.'], to: '/projects', cta: 'Browse projects', due: '2026-10-07' },
  { key: 'decision', title: 'Record your first decision with a reason', why: 'The report rewards justified choices. Writing them now saves hours later.', todo: ['Open Decisions.', 'Record: question, chosen option, why, alternatives considered.'], to: '/decisions', cta: 'Open Decisions', auto: 'decisions' },
  { key: 'supervisor', title: 'Email your supervisor and book the first meeting', why: 'The first meeting is your responsibility. It happens 8–14 Oct.', todo: ['Check Canvas for your supervisor name (expected Wed 7 Oct).', 'Email them: introduce yourself, state your idea in one sentence, propose 2–3 times between 8 and 14 Oct.', 'Complete the Selection Form 24h before the meeting.'], due: '2026-10-14' },
  { key: 'selection', title: 'Submit Project Selection on Canvas', why: 'Assignment 1. Hard deadline: Thu 15 Oct 17:00.', todo: ['Complete the Canvas Selection Form: title, main problem, inspiration, research areas, artefact, knowledge to gain.', 'Submit before deadline.'], due: '2026-10-15' },
  { key: 'tasks', title: 'Break your project into small tasks', why: 'Big projects feel impossible. Small tasks with clear "done when" do not.', todo: ['Open Tasks.', 'Add at least 5 tasks. Mark essentials "core" and extras "stretch".', 'Give each one a definition of done.'], to: '/tasks', cta: 'Open Tasks', auto: 'tasks' },
  { key: 'day', title: 'Do your first daily Start Day', why: 'A calm daily habit beats rare marathon sessions.', todo: ['Open Today.', 'Answer daily check-in: how much time, how are you feeling.', 'Answer start-of-day questions (mission, success criteria).'], to: '/today', cta: 'Start my day', auto: 'daily' },
  { key: 'outline', title: 'Draft and submit the Project Outline (worth 10%)', why: '10% module weight. Needs aims, Gantt, risks, ethics, references.', todo: ['Use Canvas template.', 'Personal target: ready by Mon 9 Nov.', 'Submit by Mon 16 Nov 17:00.'], due: '2026-11-16' },
  { key: 'logbook', title: 'Start the logbook habit (7 of 10 count)', why: '5% of the mark. Write within 24 hours of each supervisor meeting.', todo: ['After every meeting: agenda, discussion precis, own assessment.', 'Submit before Friday 23:00 close.', 'Aim for at least 7 completed entries.'], due: '2026-10-30' },
]

export const PHASE_DESCRIPTIONS: Record<string, { objectives: string; tasks: string; evidence: string; deliverables: string; mistakes: string; done: string }> = {
  'Project setup': { objectives: 'Configure the application and understand the full project lifecycle', tasks: 'Read handbook v0.9, set profile, load dates, confirm deadlines, set up backups', evidence: 'Handbook notes, saved profile, timeline loaded, Canvas deadlines confirmed', deliverables: 'Application set up, backup strategy in place, key dates known', mistakes: 'Skipping handbook, not loading official dates, no backup plan', done: 'Profile filled, all official dates loaded and checked against Canvas, backup strategy confirmed' },
  'Problem definition': { objectives: 'Define a clear, bounded, researchable CS problem', tasks: 'Write 100–200 word problem statement, list stakeholders, state CS context, scope boundary', evidence: 'Problem statement v1, one-sentence elevator pitch, scope boundaries', deliverables: 'Signed-off problem statement with stakeholders and computational context', mistakes: 'Vague problem, scope too wide, no CS angle, no stakeholders', done: 'A 100–200 word draft exists describing the problem, affected stakeholders and proposed computational context' },
  'Background research': { objectives: 'Gain foundational context of the domain', tasks: 'Collect background sources, take structured notes, identify unknowns', evidence: 'At least 5 background sources with structured notes each', deliverables: 'Foundational understanding, initial reference list', mistakes: 'Only reading, not writing notes; no synthesis of ideas', done: '5+ background sources each with: citation, key ideas, relevance to your problem' },
  'Literature review': { objectives: 'Critically review academic literature and identify the research gap', tasks: 'Collect academic sources, compare critically, synthesise, identify gap, link to your approach', evidence: '10+ analytical entries, critically compared, research gap stated', deliverables: 'Analytical literature review draft, research gap identified, Harvard citations', mistakes: 'Descriptive not analytical, no gap, no comparison of sources', done: 'Key research areas identified; sources collected and critically compared; research gap explained with relevance to your work' },
  'Requirements': { objectives: 'Define testable, prioritised project requirements', tasks: 'Elicit, prioritise (MoSCoW), write testable requirements, link to objectives', evidence: 'Requirements document with priority and test for each', deliverables: 'Requirements list, objectives map, acceptance tests', mistakes: 'Vague ("make it fast"), no priority, no acceptance test', done: 'Requirements documented, linked to project objectives, each with a concrete acceptance test' },
  'Research question / objectives': { objectives: 'Finalise focused research questions and measurable objectives', tasks: 'Draft RQs and objectives, supervisor review, refine, sign off', evidence: 'Supervisor-agreed RQs + objectives', deliverables: 'Finalised research questions, measurable objectives, success metrics', mistakes: 'Questions too broad, not measurable, no success metric', done: 'Research questions and objectives agreed with supervisor; each objective has a measurable outcome' },
  'Methodology': { objectives: 'Justify the research & development methodology you will use', tasks: 'List methods, compare alternatives, justify chosen approach, consider ethics and evaluation metrics', evidence: 'Methodology section with alternatives, rationale, evaluation plan', deliverables: 'Justified methodology + evaluation plan', mistakes: 'No justification, method doesn\'t answer the RQs, no baseline plan', done: 'Chosen method documented with alternatives considered and a clear rationale tied to research questions' },
  'System design': { objectives: 'Produce documented architecture and component design', tasks: 'Architecture diagram, module design, data model, API contracts, design decisions log', evidence: 'Architecture diagram, component designs, design decisions with rationale', deliverables: 'Architecture, designs, and decision log', mistakes: 'No diagrams, undocumented decisions, jumping to code', done: 'Architecture diagram exists; component design and key design decisions recorded with rationale' },
  'Implementation': { objectives: 'Build a working, version-controlled, buildable artefact', tasks: 'MVP → core → polish; daily commits; build pipeline; comment code where needed', evidence: 'Git history, build instructions, working build, screenshots, dev journal entries', deliverables: 'Working artefact, in git, buildable from instructions', mistakes: 'Scope creep, no commits, no build instructions, over-engineering', done: 'Core functionality works; repository is version controlled with at least weekly commits; build instructions are written and verified' },
  'Testing': { objectives: 'Rigorous testing documented, including failures', tasks: 'Test plan, unit/integration/usability/performance, document BOTH passes AND failures', evidence: 'Test cases, run results (pass and fail), bug list with fixes, screenshots', deliverables: 'Test evidence and run results', mistakes: 'Only happy path, no test evidence, no failure records', done: 'Test cases documented; passes AND failures recorded; screenshot/log evidence for each testable requirement' },
  'Evaluation': { objectives: 'Meaningful, evidenced evaluation against objectives', tasks: 'Baseline comparison, metrics collection, statistical analysis if possible, interpretation', evidence: 'Raw results, baseline vs proposed, charts, tables, qualitative analysis', deliverables: 'Comparative evaluation against baselines and research questions', mistakes: 'No baseline, unsupported claims, no interpretation', done: 'Baseline identified; metrics clearly defined; results compared; findings interpreted and limitations stated' },
  'Analysis': { objectives: 'Interpret results; connect meaning back to research questions', tasks: 'Synthesise results, interpret, link to literature, state limitations, identify threats to validity', evidence: 'Interpreted findings, linked back to RQs and literature, limitations list', deliverables: 'Analysis section and limitations', mistakes: 'Description only, no meaning, no limitations', done: 'Interpretation of each finding tied to research questions; limitations written with justifications' },
  'Dissertation/report writing': { objectives: 'Complete structured report draft with all evidence embedded', tasks: 'Write per-section while work is fresh; embed evidence; cite everything; cross-check references', evidence: 'Draft of all sections, Turnitin report under 25%, buddy read feedback', deliverables: 'Full report draft with embedded evidence and correct references', mistakes: 'Everything last minute, no cross-referencing, missing citations', done: 'All report sections drafted with evidence embedded; references cited correctly (Harvard); cross-references in the text are valid' },
  'Final refinement': { objectives: 'Polish, proofread, verify, produce submission-ready PDF', tasks: 'Spell/grammar, structure check, figures labelled, pages correct, buddy read, glossary, Turnitin', evidence: 'Checklist ticked, Turnitin read, buddy read notes addressed, final PDF generated', deliverables: 'Submission-ready PDF + code + additional resources', mistakes: 'Not enough proofreading, wrong formatting, late rush', done: 'Spell-checked, grammar-checked, buddy-reviewed; figures numbered and referenced; PDF generated and verified' },
  'Submission preparation': { objectives: 'Everything packaged for correct on-time submission', tasks: 'Check Canvas submission points, upload identical PDF to both markers, code + instructions to Additional Resources', evidence: 'Screenshots of uploads, submission receipts, final checklist', deliverables: 'All files submitted on time', mistakes: 'Missed a submission point, wrong file, after deadline', done: 'Identical PDF submitted to Supervisor AND Second Marker points; code with instructions uploaded to Additional Resources; before 15:00 Fri 9 Apr' },
  'Presentation / viva / demonstration': { objectives: 'Compulsory: deliver 20-min viva with <10 min demo', tasks: 'Book time with BOTH markers, book room, rehearse to time, pre-run slow functions, anticipate questions', evidence: 'Booking confirmations, rehearsal notes, demo plan, Q&A practice', deliverables: 'Attended viva, delivered within time, answered questions', mistakes: 'Over-running, reading from script, no rehearsal', done: 'Time arranged with both markers and room booked; demo practised to 10 minutes max; likely questions rehearsed' },
  'Final archive': { objectives: 'A complete, recoverable archive of the entire project', tasks: 'Package code, data, report, evidence, decisions, journal, references in one recoverable bundle', evidence: 'Archive bundle: zipped, SHA256, second copy stored separately', deliverables: 'Full project archive', mistakes: 'Losing code/data, no second backup, incomplete record', done: 'Project archive exists and contains: code, data, report PDF, decisions, journal, evidence links; two copies in separate locations' },
}

export const BLOCKER_SUGGESTIONS: Record<string, string> = {
  waiting_person: 'Send a brief, polite follow-up email today with specific questions; offer alternatives. If urgent, contact the module coordinator as backup.',
  waiting_info: 'Identify exactly which piece of information is missing. Check Canvas handbook and module spec. Email your supervisor with a precise question.',
  technical: 'Reduce the scope to isolate the problem. Search Stack Overflow / GitHub for the exact error message. Write it up as a development journal entry — writing it out often unblocks you.',
  unclear: 'Rewrite the task in your own words in 2 sentences. Define the smallest test that would prove progress. Ask your supervisor: "Is this interpretation correct?"',
  missing_resource: 'Find a free/open-source alternative. Ask your supervisor about lab access or departmental resources. Document the limitation so it doesn\'t invalidate your work.',
  too_difficult: 'Break into 5–10 smaller subtasks; the hardest part is usually one specific subtask. Ask for help on that one subtask, not the whole thing.',
  lack_of_time: 'Reduce scope honestly. Drop stretch tasks first, then optional, then some important — keep core. Record the trade-off as a decision.',
  other: 'Write down the blocker in a single sentence, list 3 possible recovery actions, pick the smallest one and do it now. Record it as a journal entry.',
}

export const LOST_PATHS = [
  { id: 'reqs', label: 'I don\'t know what the project requires.', go: 'handbook', title: 'Programme & handbook guidance', desc: 'Open the Handbook area to review the official requirements, grading rules and deadlines. Everything is taken directly from the handbook v0.9 PDF.' },
  { id: 'workon', label: 'I don\'t know what to work on.', go: 'next', title: 'Show me my single next action', desc: 'The Next Action engine picks your highest-priority doable task with a clear "done when". No decisions needed.' },
  { id: 'understand', label: 'I don\'t understand this task.', go: 'break', title: 'Break this task into tiny steps', desc: 'We will take the task and split it into 5–10 small subtasks, each with its own tiny definition of done.' },
  { id: 'blocked', label: 'I am blocked.', go: 'block', title: 'Let\'s resolve the blocker', desc: 'Classify the blocker type and get a concrete recovery action you can take today.' },
  { id: 'toomuch', label: 'I have too much to do.', go: 'reduce', title: 'Reduce scope calmly', desc: 'We will hide non-core tasks temporarily so you only see what must be done first.' },
  { id: 'behind', label: 'I am behind schedule.', go: 'recover', title: 'Recovery plan', desc: 'We will look at actual progress, identify the smallest path to a pass, and plan step by step.' },
  { id: 'goodenough', label: 'I started but don\'t know if it is good enough.', go: 'dod', title: 'Definition-of-done checklist', desc: 'We will open the specific definition of done for this phase/milestone/task and check it point by point.' },
]
