create table projects(id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, title text not null, objective text, created_at timestamptz default now());
create table events(id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, title text not null, date date not null, kind text not null check (kind in ('official','personal','warning','milestone')), done boolean default false, created_at timestamptz default now());
create table tasks(id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, title text not null, tier text not null default 'core' check (tier in ('core','important','optional','stretch')), status text not null default 'todo' check (status in ('todo','done')), due date, created_at timestamptz default now());
create table daily_records(id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, day date not null, mission text, objective text, biggest_win text, biggest_challenge text, learned text, first_task_tomorrow text, completed boolean default false, created_at timestamptz default now(), unique(user_id, day));
create table decisions(id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, question text not null, chosen text, reason text, alternatives text, confidence int check (confidence between 1 and 5), decided_on date default current_date, created_at timestamptz default now());
create table blockers(id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, title text not null, severity text default 'medium' check (severity in ('low','medium','high')), status text default 'open' check (status in ('open','resolved')), next_action text, created_at timestamptz default now());
do $$ declare t text; begin foreach t in array array['projects','events','tasks','daily_records','decisions','blockers'] loop
 execute format('alter table %I enable row level security', t);
 execute format('create index on %I(user_id)', t);
 execute format('create policy "own rows" on %I for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
end loop; end $$;
